# Generated by Django 4.2.7 on 2024-11-17 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0005_alter_reply_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="discussion",
            name="name",
            field=models.CharField(default="Anonymous", max_length=255),
        ),
        migrations.AddField(
            model_name="reply",
            name="name",
            field=models.CharField(default="Anonymous", max_length=255),
        ),
        migrations.AlterField(
            model_name="discussion",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
