# Generated by Django 4.2.7 on 2024-11-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_mission"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimelineEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("link", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
