# Generated by Django 4.2.7 on 2024-11-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_timelineevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="timelineevent",
            name="media_caption",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="timelineevent",
            name="media_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
