# Generated by Django 4.2.7 on 2024-11-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_spaceobject_agency_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="GovernmentSpending",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("spending_amount", models.FloatField()),
            ],
        ),
    ]
