# Generated by Django 4.2.7 on 2024-11-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_governmentspending"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GovernmentSpending",
        ),
        migrations.AddField(
            model_name="agencyprofile",
            name="annual_government_spending",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
